### ISSUE TITLE
pytest collects abstract test cases

### ISSUE THREAD

**Issue by mberr** [cthoyt/unittest-templates#1]
I want to use an intermediate abstract test case, which groups some common functionality. Using `pytest` via

```console
pytest tests/
```

these intermediate classes get recognized as tests (since they subclass `unittest.TestCase`), and thus executed leading to a test failure

```python-traceback
AttributeError: '_CommonTests' object has no attribute 'cls'
```

since the abstract classes do not have a class to test.

I see two solutions:
1. Make `GenericTestCase` not subclass from `unittest.TestCase`. This makes it necessary to add `unittest.TestCase` to each "leaf" test case, but allows arbitrary abstract intermediate layers in between which do not get executed themselves.
2. Extend `GenericTestCase` to check for presence of the `cls` attribute, and skip if not present, e.g.
 ```python
T = TypeVar("T")
class GenericTestCase(unittest_templates.GenericTestCase, Generic[T]):
    def setUp(self) -> None:
        if not hasattr(self, "cls"):
            raise SkipTest(f"No cls in {self.__class__}")
        super().setUp()
```
  This still detects the test cases, but skips each abstract one.

**Comment by cthoyt** [comment]
I really don't like needing to use these as mixins, so i'd prefer option 2.
I forgot something when I updated this. it should be 
```python
if not hasattr(self, "cls", None):
```

Or even better, since there's a flake8 error about this:
```python
try:
    self.cls
except AttributeError:
    raise SkipTest(f"No cls in {self.__class__}") from None
```
